/****************************************************************************
 *   Copyright (c) 2018 Zheng Lei (realthunder) <realthunder.dev@gmail.com> *
 *                                                                          *
 *   This file is part of the FreeCAD CAx development system.               *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Library General Public            *
 *   License as published by the Free Software Foundation; either           *
 *   version 2 of the License, or (at your option) any later version.       *
 *                                                                          *
 *   This library  is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          *
 *   GNU Library General Public License for more details.                   *
 *                                                                          *
 *   You should have received a copy of the GNU Library General Public      *
 *   License along with this library; see the file COPYING.LIB. If not,     *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,          *
 *   Suite 330, Boston, MA  02111-1307, USA                                 *
 *                                                                          *
 ****************************************************************************/

#ifndef GUI_VIEW_PARAMS_H
#define GUI_VIEW_PARAMS_H

/*[[[cog
import ViewParams
ViewParams.declare_begin()
]]]*/

#include <Base/Parameter.h>

namespace Gui {
/** Convenient class to obtain view provider related parameters

* The parameters are under group "User parameter:BaseApp/Preferences/View"
*
* This class is auto generated by ViewParams.py. Modify that file
* instead of this one, if you want to add any parameter. You need
* to install Cog Python package for code generation:
* @code
*     pip install cogapp
* @endcode
*
* Once modified, you can regenerate the header and the source file,
* @code
*     python3 -m cogapp -r ViewParams.h ViewParams.cpp'
* @endcode
*
* You can add a new parameter by adding lines in ViewParams.py. Available
* parameter types are 'Int, UInt, String, Bool, Float'. For example, to add
* a new Int type parameter,
* @code
*     ParamInt(parameter_name, default_value, documentation, on_change=False)
* @endcode
*
* If there is special handling on parameter change, pass in on_change=True.
* And you need to provide a function implementation in ViewParams.cpp with
* the following signature.
 * @code
 *     void ViewParams:on<parameter_name>Changed()
 * @endcode
 */
class GuiExport ViewParams {
public:
    static ParameterGrp::handle getHandle();

    static const bool & UseNewSelection();
    static const bool & defaultUseNewSelection();
    static void removeUseNewSelection();
    static void setUseNewSelection(const bool &v);
    static const char *docUseNewSelection();

    static const bool & UseSelectionRoot();
    static const bool & defaultUseSelectionRoot();
    static void removeUseSelectionRoot();
    static void setUseSelectionRoot(const bool &v);
    static const char *docUseSelectionRoot();

    static const bool & EnableSelection();
    static const bool & defaultEnableSelection();
    static void removeEnableSelection();
    static void setEnableSelection(const bool &v);
    static const char *docEnableSelection();

    static const long & RenderCache();
    static const long & defaultRenderCache();
    static void removeRenderCache();
    static void setRenderCache(const long &v);
    static const char *docRenderCache();

    static const bool & RandomColor();
    static const bool & defaultRandomColor();
    static void removeRandomColor();
    static void setRandomColor(const bool &v);
    static const char *docRandomColor();

    static const unsigned long & BoundingBoxColor();
    static const unsigned long & defaultBoundingBoxColor();
    static void removeBoundingBoxColor();
    static void setBoundingBoxColor(const unsigned long &v);
    static const char *docBoundingBoxColor();

    static const unsigned long & AnnotationTextColor();
    static const unsigned long & defaultAnnotationTextColor();
    static void removeAnnotationTextColor();
    static void setAnnotationTextColor(const unsigned long &v);
    static const char *docAnnotationTextColor();

    static const long & MarkerSize();
    static const long & defaultMarkerSize();
    static void removeMarkerSize();
    static void setMarkerSize(const long &v);
    static const char *docMarkerSize();

    static const unsigned long & DefaultLinkColor();
    static const unsigned long & defaultDefaultLinkColor();
    static void removeDefaultLinkColor();
    static void setDefaultLinkColor(const unsigned long &v);
    static const char *docDefaultLinkColor();

    static const unsigned long & DefaultShapeLineColor();
    static const unsigned long & defaultDefaultShapeLineColor();
    static void removeDefaultShapeLineColor();
    static void setDefaultShapeLineColor(const unsigned long &v);
    static const char *docDefaultShapeLineColor();

    static const unsigned long & DefaultShapeVertexColor();
    static const unsigned long & defaultDefaultShapeVertexColor();
    static void removeDefaultShapeVertexColor();
    static void setDefaultShapeVertexColor(const unsigned long &v);
    static const char *docDefaultShapeVertexColor();

    static const unsigned long & DefaultShapeColor();
    static const unsigned long & defaultDefaultShapeColor();
    static void removeDefaultShapeColor();
    static void setDefaultShapeColor(const unsigned long &v);
    static const char *docDefaultShapeColor();

    static const long & DefaultShapeLineWidth();
    static const long & defaultDefaultShapeLineWidth();
    static void removeDefaultShapeLineWidth();
    static void setDefaultShapeLineWidth(const long &v);
    static const char *docDefaultShapeLineWidth();

    static const long & DefaultShapePointSize();
    static const long & defaultDefaultShapePointSize();
    static void removeDefaultShapePointSize();
    static void setDefaultShapePointSize(const long &v);
    static const char *docDefaultShapePointSize();

    static const bool & CoinCycleCheck();
    static const bool & defaultCoinCycleCheck();
    static void removeCoinCycleCheck();
    static void setCoinCycleCheck(const bool &v);
    static const char *docCoinCycleCheck();

    static const bool & EnablePropertyViewForInactiveDocument();
    static const bool & defaultEnablePropertyViewForInactiveDocument();
    static void removeEnablePropertyViewForInactiveDocument();
    static void setEnablePropertyViewForInactiveDocument(const bool &v);
    static const char *docEnablePropertyViewForInactiveDocument();

    static const bool & ShowSelectionBoundingBox();
    static const bool & defaultShowSelectionBoundingBox();
    static void removeShowSelectionBoundingBox();
    static void setShowSelectionBoundingBox(const bool &v);
    static const char *docShowSelectionBoundingBox();

    static const long & DefaultFontSize();
    static const long & defaultDefaultFontSize();
    static void removeDefaultFontSize();
    static void setDefaultFontSize(const long &v);
    static const char *docDefaultFontSize();

    static void onDefaultFontSizeChanged();
//[[[end]]]

    static int appDefaultFontSize();
    static void init();

/*[[[cog
ViewParams.declare_end()
]]]*/

};

} // namespace {namespace}
//[[[end]]]


#endif // GUI_VIEW_PARAMS_H
